### ISSUE TITLE
compileAndTest.py fails

### ISSUE THREAD

**Issue by SamMallinson** [precice/openfoam-adapter#22]
Whilst following the instructions at https://github.com/precice/precice/wiki/Building, I successfully completed steps 1-4, but when I try to run the tests, I get an error (NB: I am running the tests in a virtual environment with python3.6) as shown below. 

Running on deiban-buster.

I've tried uninstalling and reinstalling numpy (from within the environment), doing an aptitude upgrade and update, but I still get the same error.

Any suggestions as to what I am doing incorrectly?

```
(precice) samuel@prandtl:/usr/local/src/sources/precice-1.1.1$ ./tools/compileAndTest.py -t                  Removing ./tests
Creating ./tests
Running:  mpirun -n 4  ../build/last/testprecice --color_output
Running 225 test cases...
Running 225 test cases...
Running 232 test cases...
Running 225 test cases...
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeErrorRuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sys' is not defined
: module compiled against API version 0xc but this version of numpy is 0xbTraceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named TestAllAction
ImportError: No module named TestAllAction
NameError: name 'sys' is not defined

ImportError(3) 15:27:29 [action::PythonAction]:160 in initialize: ERROR: Could not load python module "TestAllAction" at path "/usr/local/src/sources/precice-1.1.1/src/action/tests/"!
(0) 15:27:29 [action::PythonAction]:160 in initialize: ERROR: Could not load python module "TestAllAction" at path "/usr/local/src/sources/precice-1.1.1/src/action/tests/"!
: ImportError: No module named TestAllAction
numpy.core.multiarray failed to import
(2) 15:27:29 [action::PythonAction]:160 in initialize: ERROR: Could not load python module "TestAllAction" at path "/usr/local/src/sources/precice-1.1.1/src/action/tests/"!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sys' is not defined
ImportError: No module named TestAllAction
(1) 15:27:29 [action::PythonAction]:160 in initialize: ERROR: Could not load python module "TestAllAction" at path "/usr/local/src/sources/precice-1.1.1/src/action/tests/"!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[23789,1],0]
  Exit code:    255
--------------------------------------------------------------------------
```

**Comment by MakisH** [comment]
Hello! This issue is unfortunately in the wrong repository and others may oversee it. But for troubleshooting we prefer using our [Gitter chatroom](https://gitter.im/precice/Lobby), where we can have more interactive conversations. Let's continue there and if we find out that there is an issue/bug, open one in the [preCICE repository](https://github.com/precice/precice).

I am not sure what could be wrong in your case, but other preCICE developers may have some idea. It most probably is a python environment problem.

By the way, GitHub and Gitter use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to format the messages. Have a look at it, especially on how you can [format blocks of code](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code).
